// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MDTransaction.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MDTransaction_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MDTransaction_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ESecurityIDSource.pb.h"
#include "ESecurityType.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MDTransaction_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MDTransaction_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MDTransaction_2eproto;
namespace com {
namespace htsc {
namespace mdc {
namespace insight {
namespace model {
class MDTransaction;
class MDTransactionDefaultTypeInternal;
extern MDTransactionDefaultTypeInternal _MDTransaction_default_instance_;
}  // namespace model
}  // namespace insight
}  // namespace mdc
}  // namespace htsc
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> ::com::htsc::mdc::insight::model::MDTransaction* Arena::CreateMaybeMessage<::com::htsc::mdc::insight::model::MDTransaction>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace com {
namespace htsc {
namespace mdc {
namespace insight {
namespace model {

// ===================================================================

class MDTransaction :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.htsc.mdc.insight.model.MDTransaction) */ {
 public:
  MDTransaction();
  virtual ~MDTransaction();

  MDTransaction(const MDTransaction& from);
  MDTransaction(MDTransaction&& from) noexcept
    : MDTransaction() {
    *this = ::std::move(from);
  }

  inline MDTransaction& operator=(const MDTransaction& from) {
    CopyFrom(from);
    return *this;
  }
  inline MDTransaction& operator=(MDTransaction&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MDTransaction& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MDTransaction* internal_default_instance() {
    return reinterpret_cast<const MDTransaction*>(
               &_MDTransaction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MDTransaction* other);
  friend void swap(MDTransaction& a, MDTransaction& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MDTransaction* New() const final {
    return CreateMaybeMessage<MDTransaction>(nullptr);
  }

  MDTransaction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MDTransaction>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MDTransaction& from);
  void MergeFrom(const MDTransaction& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MDTransaction* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.htsc.mdc.insight.model.MDTransaction";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MDTransaction_2eproto);
    return ::descriptor_table_MDTransaction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string HTSCSecurityID = 1;
  void clear_htscsecurityid();
  static const int kHTSCSecurityIDFieldNumber = 1;
  const std::string& htscsecurityid() const;
  void set_htscsecurityid(const std::string& value);
  void set_htscsecurityid(std::string&& value);
  void set_htscsecurityid(const char* value);
  void set_htscsecurityid(const char* value, size_t size);
  std::string* mutable_htscsecurityid();
  std::string* release_htscsecurityid();
  void set_allocated_htscsecurityid(std::string* htscsecurityid);

  // string FITradingMethod = 23;
  void clear_fitradingmethod();
  static const int kFITradingMethodFieldNumber = 23;
  const std::string& fitradingmethod() const;
  void set_fitradingmethod(const std::string& value);
  void set_fitradingmethod(std::string&& value);
  void set_fitradingmethod(const char* value);
  void set_fitradingmethod(const char* value, size_t size);
  std::string* mutable_fitradingmethod();
  std::string* release_fitradingmethod();
  void set_allocated_fitradingmethod(std::string* fitradingmethod);

  // string SecondaryOrderID = 32;
  void clear_secondaryorderid();
  static const int kSecondaryOrderIDFieldNumber = 32;
  const std::string& secondaryorderid() const;
  void set_secondaryorderid(const std::string& value);
  void set_secondaryorderid(std::string&& value);
  void set_secondaryorderid(const char* value);
  void set_secondaryorderid(const char* value, size_t size);
  std::string* mutable_secondaryorderid();
  std::string* release_secondaryorderid();
  void set_allocated_secondaryorderid(std::string* secondaryorderid);

  // int32 MDDate = 2;
  void clear_mddate();
  static const int kMDDateFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int32 mddate() const;
  void set_mddate(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 MDTime = 3;
  void clear_mdtime();
  static const int kMDTimeFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::int32 mdtime() const;
  void set_mdtime(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int64 DataTimestamp = 4;
  void clear_datatimestamp();
  static const int kDataTimestampFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::int64 datatimestamp() const;
  void set_datatimestamp(::PROTOBUF_NAMESPACE_ID::int64 value);

  // .com.htsc.mdc.model.ESecurityIDSource securityIDSource = 5;
  void clear_securityidsource();
  static const int kSecurityIDSourceFieldNumber = 5;
  ::com::htsc::mdc::model::ESecurityIDSource securityidsource() const;
  void set_securityidsource(::com::htsc::mdc::model::ESecurityIDSource value);

  // .com.htsc.mdc.model.ESecurityType securityType = 6;
  void clear_securitytype();
  static const int kSecurityTypeFieldNumber = 6;
  ::com::htsc::mdc::model::ESecurityType securitytype() const;
  void set_securitytype(::com::htsc::mdc::model::ESecurityType value);

  // int64 TradeIndex = 7;
  void clear_tradeindex();
  static const int kTradeIndexFieldNumber = 7;
  ::PROTOBUF_NAMESPACE_ID::int64 tradeindex() const;
  void set_tradeindex(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 TradeBuyNo = 8;
  void clear_tradebuyno();
  static const int kTradeBuyNoFieldNumber = 8;
  ::PROTOBUF_NAMESPACE_ID::int64 tradebuyno() const;
  void set_tradebuyno(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 TradeSellNo = 9;
  void clear_tradesellno();
  static const int kTradeSellNoFieldNumber = 9;
  ::PROTOBUF_NAMESPACE_ID::int64 tradesellno() const;
  void set_tradesellno(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int32 TradeType = 10;
  void clear_tradetype();
  static const int kTradeTypeFieldNumber = 10;
  ::PROTOBUF_NAMESPACE_ID::int32 tradetype() const;
  void set_tradetype(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 TradeBSFlag = 11;
  void clear_tradebsflag();
  static const int kTradeBSFlagFieldNumber = 11;
  ::PROTOBUF_NAMESPACE_ID::int32 tradebsflag() const;
  void set_tradebsflag(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int64 TradePrice = 12;
  void clear_tradeprice();
  static const int kTradePriceFieldNumber = 12;
  ::PROTOBUF_NAMESPACE_ID::int64 tradeprice() const;
  void set_tradeprice(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 TradeQty = 13;
  void clear_tradeqty();
  static const int kTradeQtyFieldNumber = 13;
  ::PROTOBUF_NAMESPACE_ID::int64 tradeqty() const;
  void set_tradeqty(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 TradeMoney = 14;
  void clear_trademoney();
  static const int kTradeMoneyFieldNumber = 14;
  ::PROTOBUF_NAMESPACE_ID::int64 trademoney() const;
  void set_trademoney(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 ApplSeqNum = 15;
  void clear_applseqnum();
  static const int kApplSeqNumFieldNumber = 15;
  ::PROTOBUF_NAMESPACE_ID::int64 applseqnum() const;
  void set_applseqnum(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int32 ChannelNo = 16;
  void clear_channelno();
  static const int kChannelNoFieldNumber = 16;
  ::PROTOBUF_NAMESPACE_ID::int32 channelno() const;
  void set_channelno(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 ExchangeDate = 17;
  void clear_exchangedate();
  static const int kExchangeDateFieldNumber = 17;
  ::PROTOBUF_NAMESPACE_ID::int32 exchangedate() const;
  void set_exchangedate(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int64 TradeCleanPrice = 19;
  void clear_tradecleanprice();
  static const int kTradeCleanPriceFieldNumber = 19;
  ::PROTOBUF_NAMESPACE_ID::int64 tradecleanprice() const;
  void set_tradecleanprice(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 AccruedInterestAmt = 20;
  void clear_accruedinterestamt();
  static const int kAccruedInterestAmtFieldNumber = 20;
  ::PROTOBUF_NAMESPACE_ID::int64 accruedinterestamt() const;
  void set_accruedinterestamt(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 TradeDirtyPrice = 21;
  void clear_tradedirtyprice();
  static const int kTradeDirtyPriceFieldNumber = 21;
  ::PROTOBUF_NAMESPACE_ID::int64 tradedirtyprice() const;
  void set_tradedirtyprice(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 MaturityYield = 22;
  void clear_maturityyield();
  static const int kMaturityYieldFieldNumber = 22;
  ::PROTOBUF_NAMESPACE_ID::int64 maturityyield() const;
  void set_maturityyield(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int32 ExchangeTime = 18;
  void clear_exchangetime();
  static const int kExchangeTimeFieldNumber = 18;
  ::PROTOBUF_NAMESPACE_ID::int32 exchangetime() const;
  void set_exchangetime(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 SettlPeriod = 28;
  void clear_settlperiod();
  static const int kSettlPeriodFieldNumber = 28;
  ::PROTOBUF_NAMESPACE_ID::int32 settlperiod() const;
  void set_settlperiod(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int64 AccruedInterestOtd = 24;
  void clear_accruedinterestotd();
  static const int kAccruedInterestOtdFieldNumber = 24;
  ::PROTOBUF_NAMESPACE_ID::int64 accruedinterestotd() const;
  void set_accruedinterestotd(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 Duration = 25;
  void clear_duration();
  static const int kDurationFieldNumber = 25;
  ::PROTOBUF_NAMESPACE_ID::int64 duration() const;
  void set_duration(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 ModifiedDuration = 26;
  void clear_modifiedduration();
  static const int kModifiedDurationFieldNumber = 26;
  ::PROTOBUF_NAMESPACE_ID::int64 modifiedduration() const;
  void set_modifiedduration(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 Convexity = 27;
  void clear_convexity();
  static const int kConvexityFieldNumber = 27;
  ::PROTOBUF_NAMESPACE_ID::int64 convexity() const;
  void set_convexity(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int32 SettlType = 29;
  void clear_settltype();
  static const int kSettlTypeFieldNumber = 29;
  ::PROTOBUF_NAMESPACE_ID::int32 settltype() const;
  void set_settltype(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 HKTradeType = 30;
  void clear_hktradetype();
  static const int kHKTradeTypeFieldNumber = 30;
  ::PROTOBUF_NAMESPACE_ID::int32 hktradetype() const;
  void set_hktradetype(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 DataMultiplePowerOf10 = 31;
  void clear_datamultiplepowerof10();
  static const int kDataMultiplePowerOf10FieldNumber = 31;
  ::PROTOBUF_NAMESPACE_ID::int32 datamultiplepowerof10() const;
  void set_datamultiplepowerof10(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 BidExecInstType = 33;
  void clear_bidexecinsttype();
  static const int kBidExecInstTypeFieldNumber = 33;
  ::PROTOBUF_NAMESPACE_ID::int32 bidexecinsttype() const;
  void set_bidexecinsttype(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int64 MarginPrice = 34;
  void clear_marginprice();
  static const int kMarginPriceFieldNumber = 34;
  ::PROTOBUF_NAMESPACE_ID::int64 marginprice() const;
  void set_marginprice(::PROTOBUF_NAMESPACE_ID::int64 value);

  // @@protoc_insertion_point(class_scope:com.htsc.mdc.insight.model.MDTransaction)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr htscsecurityid_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fitradingmethod_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr secondaryorderid_;
  ::PROTOBUF_NAMESPACE_ID::int32 mddate_;
  ::PROTOBUF_NAMESPACE_ID::int32 mdtime_;
  ::PROTOBUF_NAMESPACE_ID::int64 datatimestamp_;
  int securityidsource_;
  int securitytype_;
  ::PROTOBUF_NAMESPACE_ID::int64 tradeindex_;
  ::PROTOBUF_NAMESPACE_ID::int64 tradebuyno_;
  ::PROTOBUF_NAMESPACE_ID::int64 tradesellno_;
  ::PROTOBUF_NAMESPACE_ID::int32 tradetype_;
  ::PROTOBUF_NAMESPACE_ID::int32 tradebsflag_;
  ::PROTOBUF_NAMESPACE_ID::int64 tradeprice_;
  ::PROTOBUF_NAMESPACE_ID::int64 tradeqty_;
  ::PROTOBUF_NAMESPACE_ID::int64 trademoney_;
  ::PROTOBUF_NAMESPACE_ID::int64 applseqnum_;
  ::PROTOBUF_NAMESPACE_ID::int32 channelno_;
  ::PROTOBUF_NAMESPACE_ID::int32 exchangedate_;
  ::PROTOBUF_NAMESPACE_ID::int64 tradecleanprice_;
  ::PROTOBUF_NAMESPACE_ID::int64 accruedinterestamt_;
  ::PROTOBUF_NAMESPACE_ID::int64 tradedirtyprice_;
  ::PROTOBUF_NAMESPACE_ID::int64 maturityyield_;
  ::PROTOBUF_NAMESPACE_ID::int32 exchangetime_;
  ::PROTOBUF_NAMESPACE_ID::int32 settlperiod_;
  ::PROTOBUF_NAMESPACE_ID::int64 accruedinterestotd_;
  ::PROTOBUF_NAMESPACE_ID::int64 duration_;
  ::PROTOBUF_NAMESPACE_ID::int64 modifiedduration_;
  ::PROTOBUF_NAMESPACE_ID::int64 convexity_;
  ::PROTOBUF_NAMESPACE_ID::int32 settltype_;
  ::PROTOBUF_NAMESPACE_ID::int32 hktradetype_;
  ::PROTOBUF_NAMESPACE_ID::int32 datamultiplepowerof10_;
  ::PROTOBUF_NAMESPACE_ID::int32 bidexecinsttype_;
  ::PROTOBUF_NAMESPACE_ID::int64 marginprice_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MDTransaction_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MDTransaction

// string HTSCSecurityID = 1;
inline void MDTransaction::clear_htscsecurityid() {
  htscsecurityid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MDTransaction::htscsecurityid() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.HTSCSecurityID)
  return htscsecurityid_.GetNoArena();
}
inline void MDTransaction::set_htscsecurityid(const std::string& value) {
  
  htscsecurityid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.HTSCSecurityID)
}
inline void MDTransaction::set_htscsecurityid(std::string&& value) {
  
  htscsecurityid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.htsc.mdc.insight.model.MDTransaction.HTSCSecurityID)
}
inline void MDTransaction::set_htscsecurityid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  htscsecurityid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.htsc.mdc.insight.model.MDTransaction.HTSCSecurityID)
}
inline void MDTransaction::set_htscsecurityid(const char* value, size_t size) {
  
  htscsecurityid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.htsc.mdc.insight.model.MDTransaction.HTSCSecurityID)
}
inline std::string* MDTransaction::mutable_htscsecurityid() {
  
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDTransaction.HTSCSecurityID)
  return htscsecurityid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MDTransaction::release_htscsecurityid() {
  // @@protoc_insertion_point(field_release:com.htsc.mdc.insight.model.MDTransaction.HTSCSecurityID)
  
  return htscsecurityid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MDTransaction::set_allocated_htscsecurityid(std::string* htscsecurityid) {
  if (htscsecurityid != nullptr) {
    
  } else {
    
  }
  htscsecurityid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), htscsecurityid);
  // @@protoc_insertion_point(field_set_allocated:com.htsc.mdc.insight.model.MDTransaction.HTSCSecurityID)
}

// int32 MDDate = 2;
inline void MDTransaction::clear_mddate() {
  mddate_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::mddate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.MDDate)
  return mddate_;
}
inline void MDTransaction::set_mddate(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  mddate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.MDDate)
}

// int32 MDTime = 3;
inline void MDTransaction::clear_mdtime() {
  mdtime_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::mdtime() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.MDTime)
  return mdtime_;
}
inline void MDTransaction::set_mdtime(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  mdtime_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.MDTime)
}

// int64 DataTimestamp = 4;
inline void MDTransaction::clear_datatimestamp() {
  datatimestamp_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::datatimestamp() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.DataTimestamp)
  return datatimestamp_;
}
inline void MDTransaction::set_datatimestamp(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  datatimestamp_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.DataTimestamp)
}

// .com.htsc.mdc.model.ESecurityIDSource securityIDSource = 5;
inline void MDTransaction::clear_securityidsource() {
  securityidsource_ = 0;
}
inline ::com::htsc::mdc::model::ESecurityIDSource MDTransaction::securityidsource() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.securityIDSource)
  return static_cast< ::com::htsc::mdc::model::ESecurityIDSource >(securityidsource_);
}
inline void MDTransaction::set_securityidsource(::com::htsc::mdc::model::ESecurityIDSource value) {
  
  securityidsource_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.securityIDSource)
}

// .com.htsc.mdc.model.ESecurityType securityType = 6;
inline void MDTransaction::clear_securitytype() {
  securitytype_ = 0;
}
inline ::com::htsc::mdc::model::ESecurityType MDTransaction::securitytype() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.securityType)
  return static_cast< ::com::htsc::mdc::model::ESecurityType >(securitytype_);
}
inline void MDTransaction::set_securitytype(::com::htsc::mdc::model::ESecurityType value) {
  
  securitytype_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.securityType)
}

// int64 TradeIndex = 7;
inline void MDTransaction::clear_tradeindex() {
  tradeindex_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::tradeindex() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradeIndex)
  return tradeindex_;
}
inline void MDTransaction::set_tradeindex(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  tradeindex_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradeIndex)
}

// int64 TradeBuyNo = 8;
inline void MDTransaction::clear_tradebuyno() {
  tradebuyno_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::tradebuyno() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradeBuyNo)
  return tradebuyno_;
}
inline void MDTransaction::set_tradebuyno(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  tradebuyno_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradeBuyNo)
}

// int64 TradeSellNo = 9;
inline void MDTransaction::clear_tradesellno() {
  tradesellno_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::tradesellno() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradeSellNo)
  return tradesellno_;
}
inline void MDTransaction::set_tradesellno(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  tradesellno_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradeSellNo)
}

// int32 TradeType = 10;
inline void MDTransaction::clear_tradetype() {
  tradetype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::tradetype() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradeType)
  return tradetype_;
}
inline void MDTransaction::set_tradetype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  tradetype_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradeType)
}

// int32 TradeBSFlag = 11;
inline void MDTransaction::clear_tradebsflag() {
  tradebsflag_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::tradebsflag() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradeBSFlag)
  return tradebsflag_;
}
inline void MDTransaction::set_tradebsflag(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  tradebsflag_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradeBSFlag)
}

// int64 TradePrice = 12;
inline void MDTransaction::clear_tradeprice() {
  tradeprice_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::tradeprice() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradePrice)
  return tradeprice_;
}
inline void MDTransaction::set_tradeprice(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  tradeprice_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradePrice)
}

// int64 TradeQty = 13;
inline void MDTransaction::clear_tradeqty() {
  tradeqty_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::tradeqty() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradeQty)
  return tradeqty_;
}
inline void MDTransaction::set_tradeqty(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  tradeqty_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradeQty)
}

// int64 TradeMoney = 14;
inline void MDTransaction::clear_trademoney() {
  trademoney_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::trademoney() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradeMoney)
  return trademoney_;
}
inline void MDTransaction::set_trademoney(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  trademoney_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradeMoney)
}

// int64 ApplSeqNum = 15;
inline void MDTransaction::clear_applseqnum() {
  applseqnum_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::applseqnum() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.ApplSeqNum)
  return applseqnum_;
}
inline void MDTransaction::set_applseqnum(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  applseqnum_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.ApplSeqNum)
}

// int32 ChannelNo = 16;
inline void MDTransaction::clear_channelno() {
  channelno_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::channelno() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.ChannelNo)
  return channelno_;
}
inline void MDTransaction::set_channelno(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  channelno_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.ChannelNo)
}

// int32 ExchangeDate = 17;
inline void MDTransaction::clear_exchangedate() {
  exchangedate_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::exchangedate() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.ExchangeDate)
  return exchangedate_;
}
inline void MDTransaction::set_exchangedate(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  exchangedate_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.ExchangeDate)
}

// int32 ExchangeTime = 18;
inline void MDTransaction::clear_exchangetime() {
  exchangetime_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::exchangetime() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.ExchangeTime)
  return exchangetime_;
}
inline void MDTransaction::set_exchangetime(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  exchangetime_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.ExchangeTime)
}

// int64 TradeCleanPrice = 19;
inline void MDTransaction::clear_tradecleanprice() {
  tradecleanprice_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::tradecleanprice() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradeCleanPrice)
  return tradecleanprice_;
}
inline void MDTransaction::set_tradecleanprice(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  tradecleanprice_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradeCleanPrice)
}

// int64 AccruedInterestAmt = 20;
inline void MDTransaction::clear_accruedinterestamt() {
  accruedinterestamt_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::accruedinterestamt() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.AccruedInterestAmt)
  return accruedinterestamt_;
}
inline void MDTransaction::set_accruedinterestamt(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  accruedinterestamt_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.AccruedInterestAmt)
}

// int64 TradeDirtyPrice = 21;
inline void MDTransaction::clear_tradedirtyprice() {
  tradedirtyprice_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::tradedirtyprice() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.TradeDirtyPrice)
  return tradedirtyprice_;
}
inline void MDTransaction::set_tradedirtyprice(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  tradedirtyprice_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.TradeDirtyPrice)
}

// int64 MaturityYield = 22;
inline void MDTransaction::clear_maturityyield() {
  maturityyield_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::maturityyield() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.MaturityYield)
  return maturityyield_;
}
inline void MDTransaction::set_maturityyield(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  maturityyield_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.MaturityYield)
}

// string FITradingMethod = 23;
inline void MDTransaction::clear_fitradingmethod() {
  fitradingmethod_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MDTransaction::fitradingmethod() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.FITradingMethod)
  return fitradingmethod_.GetNoArena();
}
inline void MDTransaction::set_fitradingmethod(const std::string& value) {
  
  fitradingmethod_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.FITradingMethod)
}
inline void MDTransaction::set_fitradingmethod(std::string&& value) {
  
  fitradingmethod_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.htsc.mdc.insight.model.MDTransaction.FITradingMethod)
}
inline void MDTransaction::set_fitradingmethod(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fitradingmethod_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.htsc.mdc.insight.model.MDTransaction.FITradingMethod)
}
inline void MDTransaction::set_fitradingmethod(const char* value, size_t size) {
  
  fitradingmethod_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.htsc.mdc.insight.model.MDTransaction.FITradingMethod)
}
inline std::string* MDTransaction::mutable_fitradingmethod() {
  
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDTransaction.FITradingMethod)
  return fitradingmethod_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MDTransaction::release_fitradingmethod() {
  // @@protoc_insertion_point(field_release:com.htsc.mdc.insight.model.MDTransaction.FITradingMethod)
  
  return fitradingmethod_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MDTransaction::set_allocated_fitradingmethod(std::string* fitradingmethod) {
  if (fitradingmethod != nullptr) {
    
  } else {
    
  }
  fitradingmethod_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fitradingmethod);
  // @@protoc_insertion_point(field_set_allocated:com.htsc.mdc.insight.model.MDTransaction.FITradingMethod)
}

// int64 AccruedInterestOtd = 24;
inline void MDTransaction::clear_accruedinterestotd() {
  accruedinterestotd_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::accruedinterestotd() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.AccruedInterestOtd)
  return accruedinterestotd_;
}
inline void MDTransaction::set_accruedinterestotd(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  accruedinterestotd_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.AccruedInterestOtd)
}

// int64 Duration = 25;
inline void MDTransaction::clear_duration() {
  duration_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::duration() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.Duration)
  return duration_;
}
inline void MDTransaction::set_duration(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  duration_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.Duration)
}

// int64 ModifiedDuration = 26;
inline void MDTransaction::clear_modifiedduration() {
  modifiedduration_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::modifiedduration() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.ModifiedDuration)
  return modifiedduration_;
}
inline void MDTransaction::set_modifiedduration(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  modifiedduration_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.ModifiedDuration)
}

// int64 Convexity = 27;
inline void MDTransaction::clear_convexity() {
  convexity_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::convexity() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.Convexity)
  return convexity_;
}
inline void MDTransaction::set_convexity(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  convexity_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.Convexity)
}

// int32 SettlPeriod = 28;
inline void MDTransaction::clear_settlperiod() {
  settlperiod_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::settlperiod() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.SettlPeriod)
  return settlperiod_;
}
inline void MDTransaction::set_settlperiod(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  settlperiod_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.SettlPeriod)
}

// int32 SettlType = 29;
inline void MDTransaction::clear_settltype() {
  settltype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::settltype() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.SettlType)
  return settltype_;
}
inline void MDTransaction::set_settltype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  settltype_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.SettlType)
}

// int32 HKTradeType = 30;
inline void MDTransaction::clear_hktradetype() {
  hktradetype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::hktradetype() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.HKTradeType)
  return hktradetype_;
}
inline void MDTransaction::set_hktradetype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  hktradetype_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.HKTradeType)
}

// int32 DataMultiplePowerOf10 = 31;
inline void MDTransaction::clear_datamultiplepowerof10() {
  datamultiplepowerof10_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::datamultiplepowerof10() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.DataMultiplePowerOf10)
  return datamultiplepowerof10_;
}
inline void MDTransaction::set_datamultiplepowerof10(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  datamultiplepowerof10_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.DataMultiplePowerOf10)
}

// string SecondaryOrderID = 32;
inline void MDTransaction::clear_secondaryorderid() {
  secondaryorderid_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& MDTransaction::secondaryorderid() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.SecondaryOrderID)
  return secondaryorderid_.GetNoArena();
}
inline void MDTransaction::set_secondaryorderid(const std::string& value) {
  
  secondaryorderid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.SecondaryOrderID)
}
inline void MDTransaction::set_secondaryorderid(std::string&& value) {
  
  secondaryorderid_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.htsc.mdc.insight.model.MDTransaction.SecondaryOrderID)
}
inline void MDTransaction::set_secondaryorderid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  secondaryorderid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.htsc.mdc.insight.model.MDTransaction.SecondaryOrderID)
}
inline void MDTransaction::set_secondaryorderid(const char* value, size_t size) {
  
  secondaryorderid_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.htsc.mdc.insight.model.MDTransaction.SecondaryOrderID)
}
inline std::string* MDTransaction::mutable_secondaryorderid() {
  
  // @@protoc_insertion_point(field_mutable:com.htsc.mdc.insight.model.MDTransaction.SecondaryOrderID)
  return secondaryorderid_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MDTransaction::release_secondaryorderid() {
  // @@protoc_insertion_point(field_release:com.htsc.mdc.insight.model.MDTransaction.SecondaryOrderID)
  
  return secondaryorderid_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MDTransaction::set_allocated_secondaryorderid(std::string* secondaryorderid) {
  if (secondaryorderid != nullptr) {
    
  } else {
    
  }
  secondaryorderid_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), secondaryorderid);
  // @@protoc_insertion_point(field_set_allocated:com.htsc.mdc.insight.model.MDTransaction.SecondaryOrderID)
}

// int32 BidExecInstType = 33;
inline void MDTransaction::clear_bidexecinsttype() {
  bidexecinsttype_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MDTransaction::bidexecinsttype() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.BidExecInstType)
  return bidexecinsttype_;
}
inline void MDTransaction::set_bidexecinsttype(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  bidexecinsttype_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.BidExecInstType)
}

// int64 MarginPrice = 34;
inline void MDTransaction::clear_marginprice() {
  marginprice_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MDTransaction::marginprice() const {
  // @@protoc_insertion_point(field_get:com.htsc.mdc.insight.model.MDTransaction.MarginPrice)
  return marginprice_;
}
inline void MDTransaction::set_marginprice(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  marginprice_ = value;
  // @@protoc_insertion_point(field_set:com.htsc.mdc.insight.model.MDTransaction.MarginPrice)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace model
}  // namespace insight
}  // namespace mdc
}  // namespace htsc
}  // namespace com

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MDTransaction_2eproto
